name: Build and Release ISO Images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 1,16 * *" # Run on the 1st and 16th of every month at 3:00 AM

jobs:
  build-nixiso:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build nixiso
        continue-on-error: false
        run: nix build -L .#nixosConfigurations.nixiso.config.system.build.isoImage

      - name: Upload Release Artifacts
        run: |
          release=$(date +"%Y-%m-%d")
          gh release create "$release"
          gh release upload "$release" ./result/iso/*.iso
        env:
          GH_TOKEN: ${{ github.token }}
